export default [
	{
		title: "开方工具",
		navs: [
			{
				title1: "AI智能辩证",
				title2: "",
				imgUrl: "/static/images/tool/aizn.png",
				createTime: null,
				isHot: false,
				clickNum: 0,
				isNew: false,
				disabled: false,
				id: "aizn",
				page: "/pages/home/home",
				clickEvent: "",
			},
			{
				title1: "舌象速查",
				title2: "",
				imgUrl: "/static/images/tool/sxsc.png",
				createTime: null,
				isHot: false,
				clickNum: 0,
				isNew: false,
				disabled: false,
				id: "stsc",
				page: "/pagesTool/toolList/toolList",
				clickEvent: "tongue_map_depot",
			},
			{
				title1: "经脉穴位",
				title2: "",
				imgUrl: "/static/images/tool/jmxw.png",
				createTime: null,
				isHot: false,
				clickNum: 0,
				isNew: false,
				disabled: false,
				id: "jmxw",
				page: "/pagesTool/meridianPoints/meridianPoints",
				clickEvent: "acupoint_map_label",
			},
			{
				title1: "中西医",
				title2: "病名对照",
				imgUrl: "/static/images/tool/zxybmdz.png",
				createTime: null,
				isHot: false,
				clickNum: 0,
				isNew: false,
				disabled: false,
				id: "zxybmdz",
				page: "/pagesTool/diseaseNameContrast/diseaseNameContrast",
				clickEvent: "disease_name_refer",
			},
			{
				title1: "中药",
				title2: "处方划价",
				imgUrl: "/static/images/tool/zycfhj.png",
				createTime: null,
				isHot: false,
				clickNum: 0,
				isNew: false,
				disabled: false,
				id: "zycfhj",
				page: "/pagesTool/prPrice/prPrice",
				clickEvent: null,
			},
			// {
			// 	title1: "方剂查询",
			// 	title2: "",
			// 	imgUrl: "/static/images/tool/fjcx.png",
			// 	createTime: null,
			// 	isHot: false,
			// 	clickNum: 0,
			// 	isNew: false,
			// 	disabled: true,
			// 	id: "fjcx",
			// 	page: "",
			// 	clickEvent: null,
			// },
			// {
			// 	title1: "单位换算",
			// 	title2:'',
			// 	imgUrl: '/static/images/tool/dwhs.png',
			// 	createTime:null,
			// 	isHot:false,
			// 	clickNum:0,
			// 	isNew:false,
			// 	disabled:true,
			// 	id:'dwhs',
			// 	page:'',
			// 	clickEvent: null
			// },
		],
	},
	// {
	// 	title: "特需专家",
	// 	navs: [
	// 		{
	// 			title1: "特色专科",
	// 			title2: "代客挂号",
	// 			imgUrl: "/static/images/tool/tszkdkgh.png",
	// 			createTime: "2021/07/13",
	// 			isHot: false,
	// 			clickNum: 0,
	// 			isNew: false,
	// 			disabled: true,
	// 			id: "tszkgh",
	// 			page: "/pagesAgentRegistration/index/index",
	// 			clickEvent: null,
	// 		},
	// 		{
	// 			title1: "专家到店",
	// 			title2: "",
	// 			imgUrl: "/static/images/tool/zjdd.png",
	// 			createTime: null,
	// 			isHot: false,
	// 			clickNum: 0,
	// 			isNew: false,
	// 			disabled: true,
	// 			id: "zjdd",
	// 			page: "/pagesSpecialComing/index/index",
	// 			clickEvent: null,
	// 		},
	// 		{
	// 			title1: "远程协助",
	// 			title2: "",
	// 			imgUrl: "/static/images/tool/ycxz.png",
	// 			createTime: null,
	// 			isHot: false,
	// 			clickNum: 0,
	// 			isNew: false,
	// 			disabled: true,
	// 			id: "ycxz",
	// 			page: "",
	// 			clickEvent: null,
	// 		},
	// 		{
	// 			title1: "在线跟诊",
	// 			title2: "",
	// 			imgUrl: "/static/images/tool/zxgz.png",
	// 			createTime: null,
	// 			isHot: false,
	// 			clickNum: 0,
	// 			isNew: false,
	// 			disabled: true,
	// 			id: "zxgz",
	// 			page: "",
	// 			clickEvent: null,
	// 		},
	// 		{
	// 			title1: "医案社群",
	// 			title2: "",
	// 			imgUrl: "/static/images/tool/yasq.png",
	// 			createTime: null,
	// 			isHot: false,
	// 			clickNum: 0,
	// 			isNew: false,
	// 			disabled: true,
	// 			id: "yasq",
	// 			page: "",
	// 			clickEvent: null,
	// 		},
	// 		{
	// 			title1: "医学社",
	// 			title2: "",
	// 			imgUrl: "/static/images/tool/yxs.png",
	// 			createTime: null,
	// 			isHot: false,
	// 			clickNum: 0,
	// 			isNew: false,
	// 			disabled: true,
	// 			id: "yxs",
	// 			page: "",
	// 			clickEvent: null,
	// 		},
	// 	],
	// },
	// {
	// title: "营销推广",
	// navs: [
	// 	{
	// 		title1: "海报制作",
	// 		title2: "",
	// 		imgUrl: "/static/images/tool/hbzz.png",
	// 		createTime: null,
	// 		isHot: false,
	// 		clickNum: 0,
	// 		isNew: false,
	// 		disabled: false,
	// 		id: "hbzz",
	// 		page: "/pagesMakePoster/index/index",
	// 		clickEvent: null,
	// 	},
	// {
	// 	title1: "个人包装",
	// 	title2: "",
	// 	imgUrl: "/static/images/tool/grbz.png",
	// 	createTime: null,
	// 	isHot: false,
	// 	clickNum: 0,
	// 	isNew: false,
	// 	disabled: true,
	// 	id: "grbz",
	// 	page: "",
	// 	clickEvent: null,
	// },
	// {
	// 	title1: "案例速成",
	// 	title2: "",
	// 	imgUrl: "/static/images/tool/alsc.png",
	// 	createTime: null,
	// 	isHot: false,
	// 	clickNum: 0,
	// 	isNew: false,
	// 	disabled: true,
	// 	id: "alsc",
	// 	page: "",
	// 	clickEvent: null,
	// },
	// ],
	// },
	// {
	// 	title: "经营助手",
	// 	navs: [
	// 		{
	// 			title1: "客户联系",
	// 			title2: "",
	// 			imgUrl: "/static/images/tool/khlx.png",
	// 			createTime: null,
	// 			isHot: false,
	// 			clickNum: 0,
	// 			isNew: false,
	// 			disabled: true,
	// 			id: "khlx",
	// 			page: "",
	// 			clickEvent: null,
	// 		},
	// 		{
	// 			title1: "云药房",
	// 			title2: "",
	// 			imgUrl: "/static/images/tool/yyf.png",
	// 			createTime: null,
	// 			isHot: false,
	// 			clickNum: 0,
	// 			isNew: false,
	// 			disabled: true,
	// 			id: "yyf",
	// 			page: "",
	// 			clickEvent: null,
	// 		},
	// 		{
	// 			title1: "我的微诊所",
	// 			title2: "",
	// 			imgUrl: "/static/images/tool/wdzs.png",
	// 			createTime: null,
	// 			isHot: false,
	// 			clickNum: 0,
	// 			isNew: false,
	// 			disabled: true,
	// 			id: "wdwzs",
	// 			page: "",
	// 			clickEvent: null,
	// 		},
	// 	],
	// },
	// {
	// 	title: "药品管理",
	// 	navs: [
	// 		{
	// 			title1: "采购进货",
	// 			title2: "",
	// 			imgUrl: "/static/images/tool/cgjh.png",
	// 			createTime: null,
	// 			isHot: false,
	// 			clickNum: 0,
	// 			isNew: false,
	// 			disabled: true,
	// 			id: "cgjh",
	// 			page: "",
	// 			clickEvent: null,
	// 		},
	// 		{
	// 			title1: "快速入库",
	// 			title2: "",
	// 			imgUrl: "/static/images/tool/ksrk.png",
	// 			createTime: null,
	// 			isHot: false,
	// 			clickNum: 0,
	// 			isNew: false,
	// 			disabled: true,
	// 			id: "ksrk",
	// 			page: "",
	// 			clickEvent: null,
	// 		},
	// 		{
	// 			title1: "盘点",
	// 			title2: "",
	// 			imgUrl: "/static/images/tool/pd.png",
	// 			createTime: null,
	// 			isHot: false,
	// 			clickNum: 0,
	// 			isNew: false,
	// 			disabled: true,
	// 			id: "pd",
	// 			page: "",
	// 			clickEvent: null,
	// 		},
	// 		{
	// 			title1: "出库",
	// 			title2: "",
	// 			imgUrl: "/static/images/tool/ck.png",
	// 			createTime: null,
	// 			isHot: false,
	// 			clickNum: 0,
	// 			isNew: false,
	// 			disabled: true,
	// 			id: "ck",
	// 			page: "",
	// 			clickEvent: null,
	// 		},
	// 	],
	// },
];
